services:
  - type: web
    name: sona-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn sonarea.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sonarea.settings
